ARDUINO_DIR = /home/malcolm/arduino-1.6.11
ARDMK_DIR = /home/malcolm/Arduino/Arduino-Makefile

BOARD_TAG    = teensyLC
MONITOR_PORT  = /dev/ttyACM0
ARDUINO_LIBS = Wire SoftwareSerial

# USB_TYPE = USB_SERIAL_HID

include ~/Arduino/Arduino-Makefile/Teensy.mk

