ARDUINO_DIR = /home/malcolm/arduino-1.6.11
ARDMK_DIR = /home/malcolm/Arduino/Arduino-Makefile

BOARD_TAG    = teensyLC
ARDUINO_LIBS = Wire

upload:
	make
	make reset

include ~/Arduino/Arduino-Makefile/Teensy.mk

